//! h00ligan's code-intelligence engine.

/// Human-facing build provenance embedded by `build.rs`.
pub const BUILD_IDENTITY: &str = env!("H00_BUILD_IDENTITY");

/// Exact digest of the structural indexer source/configuration closure.
pub const INDEXER_IDENTITY: &str = env!("H00_INDEXER_IDENTITY");

pub mod config;
pub mod project_binding;

#[cfg(feature = "code-intel")]
pub mod code_intel_assess;
#[cfg(feature = "code-intel")]
pub mod code_intel_audit;
#[cfg(feature = "code-intel")]
pub mod code_intel_callable_liveness;
#[cfg(feature = "code-intel")]
pub mod code_intel_calls;
#[cfg(feature = "code-intel")]
pub mod code_intel_cancellation;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_cargo;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_cursor;
#[cfg(feature = "code-intel")]
pub mod code_intel_dead;
#[cfg(feature = "code-intel")]
pub mod code_intel_dependencies;
#[cfg(feature = "code-intel")]
pub mod code_intel_diff;
#[cfg(feature = "code-intel")]
pub mod code_intel_domain;
#[cfg(feature = "code-intel")]
pub mod code_intel_find;
#[cfg(feature = "code-intel")]
pub mod code_intel_go_semantic_provider;
#[cfg(feature = "code-intel")]
pub mod code_intel_indexing;
#[cfg(feature = "code-intel")]
pub mod code_intel_inspect;
#[cfg(feature = "code-intel")]
pub mod code_intel_inventory;
#[cfg(feature = "code-intel")]
pub mod code_intel_overview;
#[cfg(feature = "code-intel")]
pub mod code_intel_payload;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_project_inputs;
#[cfg(feature = "code-intel")]
pub mod code_intel_publication;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_query;
#[cfg(feature = "code-intel")]
pub mod code_intel_query_index;
#[cfg(feature = "code-intel")]
pub mod code_intel_read;
#[cfg(feature = "code-intel")]
pub mod code_intel_rust_semantic_provider;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_semantic_cache;
#[cfg(feature = "code-intel")]
pub mod code_intel_semantic_provider;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_semantic_provider_coordinator;
#[cfg(feature = "code-intel")]
pub mod code_intel_semantic_provider_process;
#[cfg(feature = "code-intel")]
pub mod code_intel_semantic_provider_registry;
#[cfg(feature = "code-intel")]
pub mod code_intel_semantic_refresh;
#[cfg(feature = "code-intel")]
pub mod code_intel_source_search;
#[cfg(feature = "code-intel")]
pub mod code_intel_status;
#[cfg(feature = "code-intel")]
pub mod code_intel_supervisor;
#[cfg(feature = "code-intel")]
pub(crate) mod code_intel_symbol;
#[cfg(feature = "code-intel")]
pub mod code_intel_tests;
#[cfg(feature = "code-intel")]
pub mod code_intel_toolchain;
#[cfg(feature = "code-intel")]
pub mod code_intel_type;
#[cfg(feature = "code-intel")]
pub mod code_intel_workspace_semantic_provider;
#[cfg(feature = "code-intel")]
pub mod dead_pipeline;
#[cfg(feature = "code-intel")]
pub mod diff;
#[cfg(feature = "code-intel")]
pub mod dry_detection;
#[cfg(feature = "code-intel")]
pub mod edge_builder;
#[cfg(feature = "code-intel")]
pub mod enrichment;
#[cfg(feature = "code-intel")]
pub mod entry_points;
#[cfg(feature = "code-intel")]
pub mod extractor;
#[cfg(feature = "code-intel")]
pub mod git_metrics;
#[cfg(feature = "code-intel")]
pub mod graph;
#[cfg(feature = "code-intel")]
pub mod graph_overview;
#[cfg(feature = "code-intel")]
pub mod graph_query;
#[cfg(feature = "code-intel")]
pub mod graph_search;
#[cfg(feature = "code-intel")]
pub mod graph_stats;
#[cfg(feature = "code-intel")]
pub mod graph_status;
#[cfg(feature = "code-intel")]
pub mod graph_store;
#[cfg(feature = "code-intel")]
pub mod index_pipeline;
#[cfg(feature = "code-intel")]
pub mod index_state;
#[cfg(feature = "code-intel")]
pub(crate) mod indexed_source_authority;
#[cfg(feature = "code-intel")]
pub mod language;
#[cfg(feature = "code-intel")]
pub(crate) mod private_database_witness;
#[cfg(feature = "code-intel")]
pub mod reachability;
#[cfg(feature = "code-intel")]
pub mod rustc_oracle;
#[cfg(feature = "code-intel")]
pub mod scip_loader;
#[cfg(feature = "code-intel")]
pub(crate) mod scip_normalizer;
#[cfg(feature = "code-intel")]
pub(crate) mod scip_paths;
#[cfg(feature = "code-intel")]
pub mod source_discovery;
#[cfg(feature = "code-intel")]
pub mod source_materialization;
#[cfg(feature = "code-intel")]
pub mod source_search;
#[cfg(feature = "code-intel")]
pub mod structural_ir;
#[cfg(feature = "code-intel")]
pub mod watcher;
